### ISSUE TITLE
[Sunken Temple][Event] Avatar of Hakkar event

### ISSUE THREAD

**Issue by Knoox** [Atlantiss/NetherwingBugtracker#1111]
**1: Mobs spawn way to fast
2: You are able to loot blood and keep it, which lets you wipe till you have enough blood
3: If you wipe, the event keeps going and you are locked out**: 

**Server Revision 2108**:

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/3621

**Comment by Wolffenstein** [comment]
Fixed in rev 2137.

**Comment by Gemuesesueppe** [comment]
> Fixed in rev 2137.

I would way 1. is not fixed. And their aggro range is much higher than on original servers.
