### ISSUE TITLE
[spell] Missing leeway for spells when target goes slightly out of range

### ISSUE THREAD

**Issue by knasen88** [Atlantiss/NetherwingBugtracker#121]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When casting on a target and you're standing max range (say 30yd) the spell should successfully be casted if the target moves slightly out of range, and channeled spells should not be interrupted until further a certain outranging has occured (havn't tested channeled yet, but same shit applies)
**Current behaviour**:
stand 30yard, cast on target. Target patrols or w/e 1 yard away => cast failed: target too far away
**Expected behaviour**: 
Stand 30yard, cast on target. Target patrols or w/e up to (10/20% of original castrange?) 33/36 yard away and the cast still goes off. 
https://youtu.be/eJKjm0iBDbM?t=696
**Server Revision**:

**Comment by Wolffenstein** [comment]
Spell Leeway is applied when you're trying to cast spells at players. I don't know anything about it applying to creatures as well so I need source/proof for that.

**Comment by Wolffenstein** [comment]
Please reopen if you find proof for leeway working on non-player targets.

**Comment by knasen88** [comment]
So did you never actually play a caster on retail? This is 100% also an npc feature

**Comment by Wolffenstein** [comment]
Fixed in rev 2038.

**Comment by knasen88** [comment]
https://streamable.com/xtlvs NOT fixed

**Comment by Easyfraggy** [comment]
> https://streamable.com/xtlvs NOT fixed

Did you link the wrong video?

**Comment by narayagh** [comment]
This is not changed/fixed in the 2050. I definitely feels wrong and I have found hard evidence that there was a margin in TBC: http://sendvid.com/4ffvzks8

**Comment by knasen88** [comment]
uh yea i did here was the correct one https://streamable.com/jwsu2

**Comment by Wolffenstein** [comment]
Fixed in rev 2067.

**Comment by narayagh** [comment]
rev 2072
This is NOT fixed.
Please see: <div style="width:100%;height:0px;position:relative;padding-bottom:56.250%;"><iframe src="https://streamable.com/s/9g5dm/yukfv" frameborder="0" width="100%" height="100%" allowfullscreen style="width:100%;height:100%;position:absolute;left:0px;top:0px;overflow:hidden;"></iframe></div>

**Comment by narayagh** [comment]
Another proof (from the same fight nonetheless):
https://streamable.com/0335p

**Comment by Easyfraggy** [comment]
as long as issue is open it's not fixed.

**Comment by Jacksn5** [comment]
NPCs definitely also need leeway, "dodging" fireballs like this should not be possible:
[![NPCs also need Spell range leeway](http://img.youtube.com/vi/mN5ULjagaa0/0.jpg)](https://www.youtube.com/watch?v=mN5ULjagaa0 "NPCs also need Spell range leeway")

**Comment by killablink** [comment]
Also, the spell leeway that was previously working on PVP targets isn't working. So need it for PVE and PVP too

**Comment by Kantrul** [comment]
Still not working.

**Comment by Oldwal** [comment]
How the fuck is this not fixed?!

**Comment by teodinmw** [comment]
Still not working.

**Comment by Oldwal** [comment]
Still not working..

**Comment by knasen88** [comment]
looks like its fixed now?

**Comment by PabloMB95** [comment]
Its fixed

**Comment by PabloMB95** [comment]
Bugged again.

**Comment by killablink** [comment]
Bugged again.

**Comment by knasen88** [comment]
sometimes the leeway feels like maximum of 2 yards, its too short. a mob edging sometimes goes "out of range" Able to share how far it's set to atm? @devs

**Comment by ymli1989** [comment]
bugged again.

**Comment by Easyfraggy** [comment]
Leeway is working fine on my warlock.

**Comment by Brasso** [comment]
Spell leeway works for elemental shaman spells, e.g. lightning bolt and chain lightning, but not for resto shamans. The slightest change in tank position out of range of the healers will cancel the heal.

**Comment by Easyfraggy** [comment]
Could be that healing spells aren't included in leeway atm!

**Comment by killablink** [comment]
https://gfycat.com/MediumFarGodwit 
It is still definitely bugged, for everything. My warlock friend says spell leeway doesn't work on his spells, brought a shaman friend to test lightning bolt and it didn't work too as you can see. The only moment I see spell leeway SLIGHTLY working (range is still too small) is in BGs for some reason.

**Comment by Azalen** [comment]
After playing some arena yesterday I can confirm. This is still bugged and makes playing caster super aids. Tested with Fear.

**Comment by The14me** [comment]
If u pass 2/3 of the cast time the spell go off. (Rev 3441)
