### ISSUE TITLE
[Hunter]Pet name

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1460]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
After renaming pet instead of the new name it displays "Unknown", however if you put it in stable name changes back to normal.
![wowscrnshot_101018_210026](https://user-images.githubusercontent.com/43690147/46759562-04c3ba00-ccd0-11e8-945a-63ef5a671f3e.jpg)
![wowscrnshot_101018_210034](https://user-images.githubusercontent.com/43690147/46759574-09886e00-ccd0-11e8-8c9b-a670db91019f.jpg)
Possible connection to https://github.com/Atlantiss/NetherwingBugtracker/issues/240 ?
**Current behaviour**:
Pet name is displayed as Unknown
**Expected behaviour**: 
Pet name should be displayed as chosen by player/pets class
**Server Revision**: 
2152

**Comment by Lebaowski** [comment]
This bug often appears after going through portals. If you're not close to a stable master you can dismiss you pet, type /reload then call your pet back and it should be fixed.

**Comment by MartMlr** [comment]
pls fix, still happens alot!

**Comment by The14me** [comment]
Must be fixed in rev. 3460

**Comment by Wolffenstein** [comment]
It is not.

**Comment by Godmatik** [comment]
Still occurs - seems to happen when going through portals primarily

**Comment by Godmatik** [comment]
Duplicate of #7293
