### ISSUE TITLE
[NPC] Crag Stalker crash

### ISSUE THREAD

**Issue by Galawer** [Atlantiss/NetherwingBugtracker#1603]
**Description**: 
[NPC](https://www.wowhead.com/npc=4126/crag-stalker) in Thousand Needles.

**Current behaviour**:
If you haven't seen this mob during your session and it attacks you out of stealth while you have Lightning Shield up, it crashes the server every time.
Here's what you get in the combat log: 
![image](https://user-images.githubusercontent.com/1574432/46943224-7d7b9b00-d06f-11e8-8970-76c8323a2648.png)
The server crashes before the stacks on Lightning Shield decrease.
Also, when this mob evades the server sometimes freezes.

I don't know if it's just this specific mob, or if this is a general issue with reflected damage onto unseen targets.

**Server Revision**: 
Rev: 2177.

**Comment by Wolffenstein** [comment]
Fixed in rev 2179.

**Comment by Galawer** [comment]
Not fixed. Still crashes, although not as often, now freezes instead. Sometimes immediately, sometimes on evade and sometimes not at all.
https://streamable.com/6tp2p
Does seem to have something to do with Lightning Shield, never happened without it.

Also, even if the server doesn't crash or freeze, sometimes your character gets stuck in a weird state where your casts don't finish, you can use instants, but they don't work properly, for example totems don't spawn. You can't log off either and if you alt-f4 and try to log back in, it crashes the server.
https://streamable.com/4jk2o
In this clip an NPC happens to kill the mob, but you also get this after the mob resets normally.
