### ISSUE TITLE
[Talent][Hunter]Bestial Swiftness

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1708]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Talent Bestial Swiftness does not effect pet speed
video - first clip without talent, second with talent
https://streamable.com/wiqdl
**Current behaviour**:
Bestial Swiftness does not effect pet outdoor speed
**Expected behaviour**: 
Bestial Swiftness should increase pet outdoor speed by 30%
**Server Revision**: 
2186

**Comment by cah4ec182** [comment]
How about this bug guys? It still broken

**Comment by Adnel5** [comment]
Talent sometimes seems works, but very very often it stops working after entering/leaving the caves/rooms and the only way to fix it is relog/talent reset. (Dismiss Pet or using mount does not help) It is very annoying, sometimes pets is even slower than the owner/players/npc.

Pursuit speed and pet follow speed also seems to be broken. More info here:
- https://github.com/Atlantiss/NetherwingBugtracker/issues/3384
- https://github.com/Atlantiss/NetherwingBugtracker/issues/4047

**Comment by letterix** [comment]
Agreed here, seeing players run normally away from my pet is damn anoying. Def not working most of the time.

**Comment by Malevolance** [comment]
Still bugged as of 16th of July 2019, this is seriously annoying as pet speed is critical in pvp and for kiting mobs

**Comment by Wolffenstein** [comment]
Fixed in rev 3078.

**Comment by Malevolance** [comment]
The fact that i had to relog to fix my pet speed means this is definitely NOT fixed yet

**Comment by Easyfraggy** [comment]
Because the fix is not live yet check .server info for current rev. Needs server update.

**Comment by Malevolance** [comment]
Server revision 3085, curently still bugged, easy to confirm since relog seems to temporarily fix it and the movement increase is definitely noticeable

**Comment by NatsumeLily** [comment]
Rev 3119, talent is still bugged. If you enter any indoor area then leave the talent will not reapply until you relog.

**Comment by Godmatik** [comment]
Duplicate
