### ISSUE TITLE
[Spell][Priest] Power Word: Fortitude, buffing players makes them appear as low hp for me

### ISSUE THREAD

**Issue by Veloziraptor** [Atlantiss/NetherwingBugtracker#1828]
[Spell][Priest] Power Word: Fortitude

**Description**: Buffing other players makes them appear as if they had very low life. Could also be an add on issue. Using xpearl.
Player confirmed thats not his hp.

Screenshot: https://imgur.com/a/5oU6qYe

**Comment by luther112** [comment]
Not only PW:F, but also any HP increasing buff, like BoK or MotW

**Comment by Jezofine** [comment]
It's because addon doesn't know target's hp and assumes it as 100 or any % person had before buff. Hp db updates later (works the same with MobHealth and MobInfo).
Have it with Pitbull, X-Perl, ElvUI.

**Comment by luther112** [comment]
I use retail interface, no addons. Still the same bug.

**Comment by Azalen** [comment]
#760 
Proof, that it has nothing to do with addons

**Comment by ttghnw** [comment]
Yes, I confirm this is still happening and when you heal the person you get the issue below:
[#397](https://github.com/Atlantiss/NetherwingBugtracker/issues/397)

**Comment by Wolffenstein** [comment]
Fixed in rev 2211.

**Comment by Easyfraggy** [comment]
Nych still has this issue with PW:F

**Comment by nycheia** [comment]
Still happens, both with my own Fort and another priests' Fort
http://prntscr.com/law3hr
Also the health doesnt update after getting healed, as shown. Gets updated on his side though.
