### ISSUE TITLE
[NPC] Gryphon Master Talonaxe is standing in the air.

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#1881]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The most minor thing I could have ever found.
https://www.wowhead.com/npc=5636/gryphon-master-talonaxe
**Current behaviour**:
![wowscrnshot_102518_164527](https://user-images.githubusercontent.com/43505031/47509167-d15b6080-d875-11e8-9837-80caf21c24d3.jpg)
**Expected behaviour**: 
He should stand on the ground imo
**Server Revision**: 
2214

**Comment by Azalen** [comment]
#NotMyNetherwing

**Comment by Tenoutoften** [comment]
the floor is lava

**Comment by Mikik3jr** [comment]
Literally unplayable.

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/47535561-5bc6b300-d8bc-11e8-8c24-ea2e10fe44bb.png)

someone had to cuck him somehow, he is fine

**Comment by ircfelix** [comment]
Can this be closed/fixed now?

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/47680980-98e6ba00-dbc8-11e8-8481-c9351a0cdf8b.png)
i still see him fine...

i need to know what caused him to stand in the air
