### ISSUE TITLE
The Missing Diplomat / Private Hendel: Weird/bugged interaction triggered by horde character

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#1898]
https://tbc-twinhead.twinstar.cz/?npc=4966 https://tbc-twinhead.twinstar.cz/?quest=1266

[Quest] (MAYBE, read the whole thing please) The Missing Diplomat (Ally only)
[NPC] Private Hendel (probably)
![image](https://user-images.githubusercontent.com/25901582/47593939-95112880-d979-11e8-8e28-271daced727a.png)

**Description**: Aight so I was playing with a horde toon and I think it was when I pulled this npc called Private Hendel a shitfest happened, the Missing Diplomat even triggered (perhaps a sneaky ally completed the quest but I didn't see anyone) and like 8-9 Jaina & co packs arrived at the place in a quick sucession, and meanwhile the Hendel guy that I was fighting with bugged or something and kept sticking to my pet without attacking it while standing at 25% hp but wasn't dropping a single 1%, and then after a few seconds he despawned. In a couple minutes the guys at the camp respawned along Hendel, and the Jainas did aswell.

**Current behaviour**: Shitfest of immortal npcs and extra spawning npcs triggered by something that shouldn't trigger it (me pulling a mob shouldn't trigger the event related to that guy's associated quest). If it was a sneaky ally triggering it just before I pulled the mob, it shouldn't spawn 10 Jainas anyway.
EDIT: definitely not a sneaky ally, I can trigger this bug everytime by just pulling Hendel.

**Expected behaviour**: Any horde should be able to kill the guy and piss off whatever ally is on the questchain without getting an army of Jaina's on him, so for a horde it should work as it does with any other npc. 

**Server Revision**: 2214

**Comment by Tereneckla** [comment]
Fixed

**Comment by Tereneckla** [comment]
The described interaction happens if alliance starts the event and for whatever reason doesn't finish the event. (He dies/runs away etc)
When a horde then attacks Private Hendel and brings him down to ~30% he stops losing HP and every further attack spawns a set of Jaina, Pained and Archmage Tervosh NPCs.
![WoWScrnShot_010820_133846](https://user-images.githubusercontent.com/50233983/71979062-166e7700-321d-11ea-9eab-d9d1a33ee312.jpg)
Leaving that fight makes the event continue normally again and all NPCs despawn afterwards, 
albeit there is no dialogue happening and all Private Hendels spawned afterwards are bugged like this until an alliance character finishes the event.

**Comment by Godmatik** [comment]
Rev 4018 - still an issue, exactly as described above:

"The described interaction happens if alliance starts the event and for whatever reason doesn't finish the event. (He dies/runs away etc).
When a horde then attacks Private Hendel and brings him down to ~30% he stops losing HP and every further attack spawns a set of Jaina, Pained and Archmage Tervosh NPCs."

The exact quest is 1324, NPC is 4966
