### ISSUE TITLE
[Core][Combat] Parry from the back on fleeing NPC

### ISSUE THREAD

**Issue by Jacksn5** [Atlantiss/NetherwingBugtracker#209]
**Description**: 
[![Parry from the back](http://img.youtube.com/vi/sU7Lrm_1icI/0.jpg)](https://www.youtube.com/watch?v=sU7Lrm_1icI "Parry from the back")
Reporting this because it's very apparent I was behind the target and the hit should not have been able to be parried

**Server Revision**: 
[2028]

**Comment by totaemoeggerli** [comment]
https://gfycat.com/InbornRecklessCowrie

**Comment by Mikik3jr** [comment]
Defias Looter disarmed me then ran away in fear. The looter parried me 3 times in a row while I was hitting his back.

**Comment by Easyfraggy** [comment]
fixed as far as i can see

**Comment by Jacksn5** [comment]
Not fixed, it seems as though the mob running away isn't actually facing the way it's running as it also can not be attacked with "behind the mob" abilities like Backstab/Shred.

**Comment by Godmatik** [comment]
Duplicate https://github.com/Atlantiss/NetherwingBugtracker/issues/1565
