### ISSUE TITLE
Stuck in combat at Forge Camp: Mageddon

### ISSUE THREAD

**Issue by DeadManStomping** [Atlantiss/NetherwingBugtracker#2114]
**Description**:  Can't leave combat in this zone

**Current behaviour**:  once you kill a fel  cannon you'll be locked in combat and can't fly out of the zone.

**Expected behaviour**:  Killing the fel cannon drops combat

**Server Revision**:

**Comment by Easyfraggy** [comment]
Fixed on next update also: https://github.com/Atlantiss/NetherwingBugtracker/issues/2028

**Comment by KevinTyrrell** [comment]
Not sure if update was applied, but as of 30 minutes ago this bug still persists.

[Twitch Clip](https://clips.twitch.tv/BrightColdbloodedTruffleFutureMan)

**Comment by Easyfraggy** [comment]
It's not updated till Emtec is done removing ACE etc
