### ISSUE TITLE
[Quest][Hellfire Peninsula] Avruu's Orb

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#2119]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
https://fr.wowhead.com/npc=17085/aeranas#english-comments
https://www.youtube.com/watch?v=pGJ_bxkkc8c
**Description**: 
After summoning Aeranas, you currently have to down him to 1% for him to get friendly. Also, the time the NPC stays before disappearing (to complete the quest) is really short atm.
**Current behaviour**:
Aeranas gets friendly at 1% hp.
**Expected behaviour**: 
Aeranas should get friendly at 30% hp.
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2248.

**Comment by sk6868** [comment]
I'm sorry but this bug still exists as of July 26, 2024.  I can reproduce it in Karazhan and Netherwing servers.

**Comment by Godmatik** [comment]
Unable to reproduce @sk6868 

Just tested and he went friendly @ 30% health for me just fine

**Comment by sk6868** [comment]
I am leveling a new toon which is just about to do the quest.  I will record a video showing the bug.

**Comment by sk6868** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2135 @Godmatik
