### ISSUE TITLE
[quest] The infested protectors

### ISSUE THREAD

**Issue by sifiuocz** [Atlantiss/NetherwingBugtracker#2181]
**Description**: 
Rotting Forest-Rager and Infested Root-Walker don't spawn the Wood Mite NPCs when pets do the killing blow.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 
2244

**Comment by Evolvee** [comment]
they spawn only when a player who has the quest gets the kill...

thats how all npcs on the entire server that have similar conditions work tho, this would be a global core issue -- i guess pets should be counted same as their owners

**Comment by mhdemn** [comment]
oi! server revision 2255
I confirm that pet killing blows do not summon the mites. Furthermore, in this [video](https://youtu.be/138xr8r3RKY) you can see the Wood Mites themselves are a little buggy too, as not all of them give credit for their kill, and it doesn't depend on whether the hunter or the pet kills them. As a sidenote, it seems AOEing all the mites down at the same time always does the trick and makes sure you get every kill credit.

**Comment by Wolffenstein** [comment]
Fixed in rev 3414.

**Comment by timmon123** [comment]
Bug is still there on Karazhan Realm. Just wanted to report it but found this issue. As explained by OP (Killing blow of pet doesnt spawn, and Pet killing Wood mite dont count for quest)
