### ISSUE TITLE
[Dungeon][The Slave Pens][NPC][Spell] Coilfang Defender - Spell Reflection

### ISSUE THREAD

**Issue by Kaini27** [Atlantiss/NetherwingBugtracker#2486]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Spell Reflection by Coilfang Defender- encases the caster in a magical shield, causing spells to be reflected back upon their target 50% of the time.

**Current behaviour**: Reflected spells dont do any damage, tested on fireballs

**Expected behaviour**: Half of the spells casted suppose to be reflected with full damage done back on caster.

**Server Revision**: 2268

**Comment by Wolffenstein** [comment]
Fixed in rev 2286.

**Comment by nycheia** [comment]
This still doesnt reflect spells damage back to you. https://clips.twitch.tv/FunnyAwkwardChickpeaPermaSmug

I do not know what triggers it, but our mage kept casting through it, and i could as well

**Comment by knasen88** [comment]
The damage is prevented to the mob but you still take damage. Same with the naga boss that goes between some distilleries occasionally doing spell shield ( warlord kalithresh)

**Comment by nycheia** [comment]
> The damage is prevented to the mob but you don't take any damage. Same with the naga boss that goes between some distilleries occasionally doing spell shield ( warlord kalithresh)

As you can see on the clip i posted, i did not take damage.

**Comment by Manaci** [comment]
Fixed
