### ISSUE TITLE
[Talent][Paladin] Light's Grace

### ISSUE THREAD

**Issue by ahlens** [Atlantiss/NetherwingBugtracker#2490]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
There is 0,5 - 1 sec delay before [Light's Grace](http://db.hellfire-tbc.com/?spell=31836) is applied to our character as a buff.

**Current behaviour**:
If we want to use Holy Light in quick succesion, the second spell will still have 2.5 sec cast time instead of 2.0. You need to wait that little delay in order to have next spell casting time reduced by 0.5 sec.

Take a look at video.
https://vimeo.com/user9632932/review/299845419/7f3d31ea22

**Expected behaviour**: 
I suppose it should be applied immediately after first cast is complete.

**Server Revision**: 
2270

**Comment by Wolffenstein** [comment]
Fixed in rev 2289.

**Comment by Ychap** [comment]
This bug still exists as [ahlens](#issue-379101419) discriped.

**Comment by Ychap** [comment]
Talent works for 3 days now. :smiley:
Thanks to the devs. :+1:
