### ISSUE TITLE
Daphne Stilwell is missing

### ISSUE THREAD

**Issue by knugen1234** [Atlantiss/NetherwingBugtracker#277]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Daphne Stilwell is not at her farm in Westfall
**Current behaviour**:
MIA
**Expected behaviour**: 
She should be walking about around her farm in Westfall
**Server Revision**: 
2032

**Comment by Wolffenstein** [comment]
Fixed in rev 2037.

**Comment by knugen1234** [comment]
I just logged on and checked and she still appears to be missing? (I tried deleting my cache folder and whatnot)

**Comment by knugen1234** [comment]
So after doing some researching i found that Daphne do spawn however she despawns immediately. Here's a video of it happening, you can see her (de)spawn at 00:03, 00:53 and 1:43
https://youtu.be/2NPkG9BhtzE

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/45969471-12244780-c034-11e8-814e-6ad69bf9b108.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 2060.
