### ISSUE TITLE
[Items] Engineering training dummies leave no lootable corpse behind

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#2882]
**Description**: [Advanced Target Dummy](https://db.excalibur.ws/?item=4392), [Masterwork Target Dummy](https://db.excalibur.ws/?item=16023) and [Target Dummy](https://db.excalibur.ws/?item=4366) are supposed to leave a corpse you can loot when they die (due to a mob killing them or by autodestructing after their fixed duration). Also, they cast an aoe taunt-thing both on summon and every few seconds that get monsters to attack them instead of the player.

**Current behaviour**: Two issues with them:

- They do not leave a corpse behind. They should leave one behind that you can loot to get things like Fused Wiring.

- They are not casting their taunt. I forgot to hit record but they are seen by enemies, so if you spawn one in vision of an off-combat enemy it will attack the dummy; but when the mobs are engaged, even if you have no extra threat built on their tables the dummy won't do anything.

You can see [here](https://youtu.be/Q4ZxyEJwzpg) that currently when the 15 seconds pass the dummy despawns, but doesn't die.

And [here](https://youtu.be/jT_cVuMw3zU) that even if killed there's no body left.

**Expected behaviour**: 

- Lootable corpse when they die. They die both from damage and from time runout, not just despawn.

- Visual and audible aoe taunt casts both on summon and every few seconds.

**Server Revision**: 2339

**Comment by samzispheq** [comment]
True this target dummy and advanced target dummies should be lootable. They should drop fused wiring

**Comment by devo6969** [comment]
Zero videos on these items only comments on Wowhead about the drops from vanilla. Can confirm still nothing dropping just despawns.

https://classic.wowhead.com/item=4392/advanced-target-dummy#comments
"Just spent 30 mins and blew up 10x Advanced Target Dummy."
Here's what I got:
1x Fused Wiring
6x Iron Strut
6x Gyrochronatom
7x Bronze Framework
18x Heavy Leather

**Comment by Handbanana69** [comment]
This is still an issue almost two years later. Please fix this, fused wiring is very hard to come by.

**Comment by Handbanana69** [comment]
Bumping this again

**Comment by Handbanana69** [comment]
B U M P

**Comment by Wolffenstein** [comment]
Fixed in rev 3558.

**Comment by sasadubi** [comment]
@Wolffenstein  Is this fixed? I opened new ticket because this is still an issue.

**Comment by sasadubi** [comment]
Bump

**Comment by BamboozleNW** [comment]
Bump. Need these pretty bad

**Comment by sasadubi** [comment]
@Wolffenstein
