### ISSUE TITLE
[Dungeon][The Slave Pens]Coilfang Defender patrol route

### ISSUE THREAD

**Issue by feuerkind** [Atlantiss/NetherwingBugtracker#3227]
**Description**: 
The two Coilfang Defenders after the second boss take an awkward patrol route through the pack they should be going around.
**Current behaviour**:
https://youtu.be/PWpebojIhMA?t=705
**Expected behaviour**: 
https://youtu.be/YvYiRsCV9FM?t=120
**Server Revision**: 
2382

**Comment by Easyfraggy** [comment]
Neither of the two videos show the mobs at any similar positions - did you link the right videos?

**Comment by feuerkind** [comment]
Sorry, wrong timestamp on the current one. Fixed now.

**Comment by devo6969** [comment]
The patrolling Naga's are suppose to go around the center pack, at the moment they are going through the pack. Also seems they were suppose to patrol a little further up the ramp.

Retail cata (Don't see the mobs probably because they are further up and bad Environmental Distance)
-  https://youtu.be/9F8HZPWHtgM?t=1123

Retail BFA (Full patrol of the Defenders) - https://youtu.be/C8P07oNLdto?t=5

**Comment by Godmatik** [comment]
Rev 4018 - still an issue - their waypoint movement needs to be improved regardless it is slightly odd
