### ISSUE TITLE
Mind Vision has an incorrect range limitation and doesn't allow jumping 

### ISSUE THREAD

**Issue by Tuwz** [Atlantiss/NetherwingBugtracker#3507]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Mind Vision has a limited range and you are not able to use it on a party target further than 100y from you. 

**Current behaviour**: The spell is cast, but the camera doesn't move to the target location. In addition, when you manage to cast Mind Vision on someone, you can't jump to another target by recasting it.

**Expected behaviour**: You should be able to cast the spell on anyone who is on the same continent, and you should also be able to jump from target to target without any range limit at all, as the tooltip is stating "Unlimited range". 

Here is a video of the expected behaviour of the Mind Vision, recorded on a Wotlk server.
https://youtu.be/tiF0gtsIEtk

**Server Revision**: Content Patch 203

**Comment by Wolffenstein** [comment]
Fixed in rev 2461.

**Comment by Tuwz** [comment]
Hi,

While the latest rev fixed the target jumping wth mind vision, the range issue is still to be adressed. Currently, you can't use Mind Vision on a party target who is 100y away from you. When you are jumping targets as well, you can't go further than 100y from the actual position of your priest.

The expected behaviour would be to virtually move the priest location to the target he is casting mind vision on, so the priest can see NPC, nodes, objects like if he was on his target's location. It should also not have a range limit as long as the priest and his target are on the same continent (and by continent i mean server, like Outland and Exodar are considered same continent by the game).

The only way for the priest's target to break Mind Vision would be to use Divine Shield, Cloak of Shadows or to change continent, enter battleground  or a dungeon. 

https://www.youtube.com/watch?v=u4NY4EXchvA
You can see on that video that the priest is using Mind Vision on a night elf flying from Stormwind to Westfall. After the flight is completed, the priest targets a new player in Westfall and is able to jump on his vision by targetting him and recasting the spell.

![image](https://user-images.githubusercontent.com/45247502/50203702-b03d5a80-0362-11e9-9c1a-953b6862d4cf.png)
Here is also the top wowhead comment from 2.0, explaining how the spell is supposed to work.

**Comment by Tuwz** [comment]
Here is the 2007 wow wiki page about Mind Vision as well:

http://wowwiki.wikia.com/wiki/Mind_Vision?oldid=1017298

**Comment by Tuwz** [comment]
Hello,

While the range on jumping seems fixed, I still can't cast Mind Vision on people within the range. I tried from Auchindoun to Shattrath and from Stormwind to IF, didn't work for some reason.

**Comment by Tenoutoften** [comment]
It's not been updated. Use .server info to see which server rev you are on. Current server rev is 2462, this is fixed with 2468 -> you need to wait for server update to test
