### ISSUE TITLE
[Karazhan][Spell](Netherspite) Empowerment

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#3630]
**Description**: 
Topic is related to the Empowerment ability Netherspite will use shortly after summoning his portals and its functionality.

**Current behaviour**:
It will sometimes not boost the boss' damage even if the (de)buff is on Netherspite. Sometimes took 2,3k damage when I was tanking him in the red beam.
The effect on the boss also doesn't disappear once the boss enters phase 2.

**Expected behaviour**: 
Should always increase the boss' damage while the (de)buff is active. The effect should end once the boss enters phase 2.
Link to comment in bug report with evidence of the boss with empowerment in banish phase: https://github.com/Atlantiss/NetherwingBugtracker/issues/3632#issuecomment-449670025

**Server Revision**: 
2485

**Comment by Wolffenstein** [comment]
Fixed in rev 2493.

**Comment by AxeCell** [comment]
As of server revision 2526 the empowerment does not increase the white damage the boss does. Unsure if it occurs 100%, but we did two attempts without him doing any more damage.

**Comment by Kuska101** [comment]
Also, he still do not drop empowerment in phase 2. And he still try to reapply it after the beams reappear.
Clip (not mine, hope the dude dont mind?) https://clips.twitch.tv/ExpensiveAbrasiveMinkAMPEnergyCherry

**Comment by Wolffenstein** [comment]
I don't see the empowerment on that clip?

**Comment by Kuska101** [comment]
oh, sorry, i've mistaken an icon of empowerment with another, it works as intended.

**Comment by Drayo** [comment]
This can be closed, it properly increased his auto attack damage for us in the last few runs.
