### ISSUE TITLE
Benedict's Chest does not give loot

### ISSUE THREAD

**Issue by sweetbakery** [Atlantiss/NetherwingBugtracker#3833]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: It's a bug related to a chest.

**Current behaviour**: When you open Benedict's Chest with Benedict's Key, nothing happens.

**Expected behaviour**:  When you open Benedict's Chest with Benedict's Key It should give you a letter that would trigger a quest to Razor Hill.

**Server Revision**: 2592

**Comment by dmrljes** [comment]
It also doesn't work for me. But looking from other servers, you need to wait because of its respawn and you dont actually know when it's respawned.

**Comment by IGNPoint** [comment]
Still doesn't work.

**Comment by raethkcj** [comment]
Still doesn't work. 

When a player loots the item inside (Admiral's Orders), the chest should instantly despawn and  trigger a short respawn timer.

If you open a chest that has already been unlocked by another player, it should not consume your key.

Currently the chest consumes your key but does not contain any loot, and also does not despawn.

**Comment by danbopes** [comment]
This is currently still an issue @wtRCH

**Comment by danbopes** [comment]
@Wolffenstein I was able to confirm/reproduce this issue on the PTR.

1. Login 2 toons:
2. `.additem 4882` (Benedict's key, to both players)
3. Loot the chest on one toon (Making sure to Shift+Click or Disable Auto Loot). Leave Aged Envelope in the chest
4. Loot the chest on the other toon (Chest is empty, unable to be looted)

**Comment by danbopes** [comment]
@wtRCH I recommend high priority, as this may be the source of a lot of the related issues (Empty nodes), and loot bugs.

**Comment by Manaci** [comment]
Fixed

**Comment by ghost** [comment]
This is still broken, tried to loot it as of 21/12/2020 and the same issue is happening.
