### ISSUE TITLE
(Quest) [Ashenvale] Torek's Assualt:

### ISSUE THREAD

**Issue by Sunethy** [Atlantiss/NetherwingBugtracker#4111]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Torek doesn't show up so i can't accept quest

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Sylphren** [comment]
Can confirm. Waited 45 minutes and no spawn. After I left, I continued to see people in General chat saying he wasn't spawning.

**Comment by duzyizly** [comment]
Done this quest at 09.01.19 - so looks like new issue.

**Comment by wtRCH** [comment]
@aresbrutus

**Comment by Braderman88** [comment]
I can confirm this still an issue today. Waited for Torek to spawn between 07:30 server time until 08:05 and he did not.

**Comment by Manaci** [comment]
Fixed
