### ISSUE TITLE
[NPC][Quest] Doctor Vomisa, PH.T.

### ISSUE THREAD

**Issue by Anduyon** [Atlantiss/NetherwingBugtracker#4122]
**Description**: 
Npc is not letting us turn in the quest Doctor Vomisa, PH.T. 
**Current behaviour**:
https://imgur.com/a/y4DjufA
The npc does not have an option to turn in this quest. http://db.hellfire-tbc.com/?quest=10247
He can be talked to like he would be if you didn't have the quest.
**Expected behaviour**: 
You should be able to turn in the quest and get the follow up http://db.hellfire-tbc.com/?quest=10248
**Server Revision**: 
2605

**Comment by lhevraz** [comment]
Still uncompletable

**Comment by femtaur** [comment]
^ same status

**Comment by Steverus1** [comment]
can confirm, this quest is not doable

**Comment by ttghnw** [comment]
broken

**Comment by AWIDIUS** [comment]
Still not working

**Comment by Jalapan** [comment]
not working rev3972

**Comment by AWIDIUS** [comment]
Will this ever get fixed ? I understand there are other important things to do, but its opened for more than month in high prio issues and still nothing. Appreciate Evolve's effort tho.

**Comment by Wolffenstein** [comment]
Fixed in rev 2835.

**Comment by Jalapan** [comment]
@Wolffenstein this issue is still not fixed, players spawn multiple "negatrons" and it dosent despawn.
