### ISSUE TITLE
[Spell][Hunter] Feign Death doesn't work

### ISSUE THREAD

**Issue by Buskmurvel** [Atlantiss/NetherwingBugtracker#429]
The animation occurs, but it doesn't have any effect on monsters. They keep hitting you.

**Comment by Wolffenstein** [comment]
Fixed in rev 2090.

**Comment by Thorgrimme** [comment]
This is still not working as it should, posting a video where u can see me attack a mob it "gouges" my pet and runs for me, i FD and still the mob attacks me, it should go for the pet as soon as i FD as it should consider me dead. https://doc-10-60-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/ca398k62fso48nqb4p4urcdjtlbrtdtj/1539820800000/00124595452018968064/*/1m3vXZBgOKyZO8R_heN07PQSQ2-k6KHVT

**Comment by ayrb13** [comment]
current behavior:
https://youtu.be/lV1g6_af9M0
