### ISSUE TITLE
Healing aggro on CC

### ISSUE THREAD

**Issue by femdead** [Atlantiss/NetherwingBugtracker#4554]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2002

broken atm, not fixed

**Comment by Azalen** [comment]
yep, broken again - I think it was fixed at some point.

**Comment by Mikik3jr** [comment]
It is still happening. On the 2 pictures the mob is targeted and I have 0 threat on it. I heal the tank, then I generate threat on the hard CC-d target.
![wowscrnshot_020919_104644](https://user-images.githubusercontent.com/43505031/52527447-e8a94700-2cc8-11e9-89b3-f21fc5f60a64.jpg)
![wowscrnshot_020919_104646](https://user-images.githubusercontent.com/43505031/52527450-ea730a80-2cc8-11e9-96f5-543f21e312d9.jpg)

Revision 2771

**Comment by Easyfraggy** [comment]
Threat meters aren't a representation of the server threat - What your addon shows doesn't reflect what the server has at all.

**Comment by Mikik3jr** [comment]
But I don't heal before they are CCd, and after CC is over they attack me.
