### ISSUE TITLE
[Hunter][Spell] Multi-shot/steady shot interaction with melee attacks

### ISSUE THREAD

**Issue by Zarant** [Atlantiss/NetherwingBugtracker#4875]
Multi-shot and steady shot are currently resetting the melee swing timer.

As evidenced by the clip below from retail tbc, both spells should not reset the melee swing timer.

https://youtu.be/FAz6E6W4T-I?t=605 33 frames (1.1 seconds) between steady shot and raptor strike
https://youtu.be/FAz6E6W4T-I?t=760 21 frames (0.7 seconds) between steady shot and raptor strike

https://youtu.be/FAz6E6W4T-I?t=767 - You can see both main hand and off hand attacks going off after a multi shot

Keep in mind that the hunter on these clips is using the S3 main hand (2.6 speed), as you can see, raptor strike is a main hand attack, and the interval between a ranged spell and raptor strike suggests that the melee swing cooldown should not be reset.

Server revision: 2761

**Comment by Zarant** [comment]
As of revision 3483 this issue still persists.

**Comment by Wolffenstein** [comment]
Fixed in rev 3694.

**Comment by RichSteini** [comment]
It is only partly fixed, the issue still persists every second melee swing. 

Event chain to reproduce: Auto Shot -> Steady Shot -> Melee Swing (great goes off instantly) -> Auto Shot -> Steady Shot -> Auto Shot -> Melee Swing (does not go off instantly as it should). 

It still has something to do with Steady Shot, because the second Melee Swing would go off instantly if you don't cast the second Steady Shot in the event chain.

**Comment by RichSteini** [comment]
Fixed in rev 3697.
