### ISSUE TITLE
Arcanite bar have no cd

### ISSUE THREAD

**Issue by nkv42** [Atlantiss/NetherwingBugtracker#4885]
Arcanite bar have no cd. CD was removed in 2.4.0. Old was 23 hours.

https://wowwiki.fandom.com/wiki/Transmute:_Arcanite

**Comment by Wolffenstein** [comment]
Fixed in rev 2776.

**Comment by koychevd** [comment]
Still does not show the CD. Also the revision probably overwrote the existing CD allowing me to transmute arcanite why I still had CD tooltip for the other transmutes.

**Comment by lynxzor** [comment]
It's a 24hr cd in 2.0, and then 23hrs from 2.1. I thought all these cd's were imlemented in [#2993](https://github.com/Atlantiss/NetherwingBugtracker/issues/2993)

**Comment by Drayo** [comment]
No offense, but changing this is honestly ridiculous, stuff like this just should not be changed WEEKS after the launch.

I personally don't care about arcanite, but this is just unfair to new players. Oversights like these should be ignored and simply noted for the future.
