### ISSUE TITLE
[Raid][Karazhan] Ethereal Spellfilcher

### ISSUE THREAD

**Issue by itsjojotbh** [Atlantiss/NetherwingBugtracker#4888]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Ethereal Spellfilcher's debuff Spatial Distortion doesn't reduce stats
**Current behaviour**:
Intellect and Spirit aren't being reduced by the debuff
Some evidance: https://cdn.discordapp.com/attachments/260876123091501057/542883019342479401/WoWScrnShot_020619_225034.jpg
As you can see my intellect and spirit is not reduced while the debuff is on me
**Expected behaviour**: 
Intellect and spirit should be reduced by 3% per stack
**Server Revision**: 
2770

**Comment by Wolffenstein** [comment]
Fixed in rev 2777.

**Comment by ircfelix** [comment]
still not working. also Ethereal Spellfilcher cast the melee debuff but I >believe< they should only use the int/spi debuff.

**Comment by ircfelix** [comment]
For clarification:
The mob does the debuff and stacks it, but the debuff does nothing.

**Comment by devo6969** [comment]
There is only one that currently uses the melee debuff and its the last one heading towards the chess room. The rest use the intel/spirit debuff and it does work.

PTR rest of Spellflicher - https://www.youtube.com/watch?v=aeGYCZBNpWI
PTR Melee debuff spellflicher - https://www.youtube.com/watch?v=PPn8oKe4Lfo

https://www.wowhead.com/npc=16545/ethereal-spellfilcher#comments
"Reduces intellect and spirit (stacking effect, 3% increments), also aoe arcane bolts"

**Comment by Tereneckla** [comment]
Correction on devo's findings:
It is random if a Spellfilcher has the Int/Spi or the Str/Agi debuff
They should only do Int/Spi though

**Comment by Godmatik** [comment]
Still occurs, just ran Kara, a Spellflicher reduced Str/Agi instead of Int/Spirit

**Comment by Wolffenstein** [comment]
Debuff seems to work fine - it reduces your stats if you watch your character sheet. And yes, Each Spellfilcher determines whether it will cast Str/Agi or Int/Spirit reduction on respawn, it's random and that's correct.
