### ISSUE TITLE
[Spell][Paladin] Seal of Righteousness coefficient

### ISSUE THREAD

**Issue by redghost4** [Atlantiss/NetherwingBugtracker#5225]
Seal of righteousness is supposed to scale dynamically based on weapon speed. The scaling should be:

9.2% per 1.0 weapon speed with a 1H weapon
10.8% per 1.0 weapon speed with a 2H weapon

Sources:

https://wowwiki.fandom.com/wiki/Spell_power_coefficient?oldid=1221571
https://wowwiki.fandom.com/wiki/Spell_power_coefficient?oldid=783588

It's also referenced in TBC versions of DrDamage addon: 
Addons/DrDamage/data/Paladin.lua:
![image](https://user-images.githubusercontent.com/48016481/53410675-bab04c00-39c4-11e9-915d-cd8bd2390aa4.png)

**Current behaviour**:

Seal of Righteousness (Rank 3) is scaling exactly the same no matter the weapon speed. I did these tests:

1. Equip a **3.2s 2H weapon**, use SoR and check it's damage. Then use Judgement of the Crusader (+58 holy damage) and see the damage increase. **Damage went from 27 to 37. (+10 increase in damage)**

![image](https://user-images.githubusercontent.com/48016481/53410870-55108f80-39c5-11e9-9ecf-3b507860a5dc.png)

![image](https://user-images.githubusercontent.com/48016481/53410889-66f23280-39c5-11e9-98bd-677d814755e7.png)

2. Equip a **1.7s 1H weapon**, use SoR and check it's damage. Then use Judgement of the Crusader (+58 holy damage) and see the damage increase. **Damage went from 11 to 21. (+10 damage again)**

![image](https://user-images.githubusercontent.com/48016481/53410916-7bcec600-39c5-11e9-8d6f-aa96031813fa.png)

![image](https://user-images.githubusercontent.com/48016481/53410931-88531e80-39c5-11e9-99cb-926acbc6b9c9.png)

**Expected behaviour**: 

Damage increase should scale differently, even if it's a lower rank (level 18 spell, it should be affected by the pre-lvl 20 spell coefficient penalty).

It doesn't look like weapon speed is affecting SoR damage at all.

I could not test it in higher ranks of the spell.

**Server Revision**: 

2844

**Comment by Wolffenstein** [comment]
Fixed in rev 2847.

**Comment by redghost4** [comment]
my man

**Comment by redghost4** [comment]
In-game .server info command says we're in rev 2850 but the bug is still there. Still getting the same numbers.

Did the fix affect all SoR ranks?

**Comment by redghost4** [comment]
@Wolffenstein ingame rev 2851, still getting exactly the same scaling with a 1.6s 1H and a 3.2s 2H. Tested ranks 3 and 4.

**Comment by Wolffenstein** [comment]
And how much spell power do you have?

**Comment by Wolffenstein** [comment]
Fixed in rev 2856.
