### ISSUE TITLE
[Hunter] [Pet] [Scorpid Poison] Does not receive Spell Bonus damage.

### ISSUE THREAD

**Issue by gunzbngbng** [Atlantiss/NetherwingBugtracker#5241]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The hunter pet scorpid has a spell called "Scorpid Poison."  Pets receives a certain amount of spell bonus based on the hunter's AP.  Scorpid Poison should scale with the Spell Bonus.

**Current behaviour**: Scorpid Poison does not scale at all, only dealing it's base damage.  Max rank deals 11 damage per stack every 2 seconds.

**Expected behaviour**: Scorpid Poison should get a coefficient bonus to it's dot damage.  I believe the coefficient to be 15% spread over the duration of each dot stack.  This video is from TBC and shows the scorpid's poison ticking at ~17 damage per stack every 2 seconds.  At five ticks per dot duration, this amounts to ~30 total bonus damage per stack.  A PvP geared, non raid buffed hunter's pet has about 200 spell bonus.  The math comes out to 15%.
https://youtu.be/VhCI3DDvGGU?t=643

**Server Revision**: 2851

**Comment by towneh** [comment]
Research: https://www.engadget.com/2007/08/08/bigredkitty-the-whole-scorpid-thing/

**Comment by gunzbngbng** [comment]
Nice job finding actual documentation.

**Comment by Wolffenstein** [comment]
Fixed in rev 2856.

**Comment by gunzbngbng** [comment]
Hey, today's patch changed something, but didn't fix it.

**Description**: Scorpid Poison should be gaining .4286 of the pet's Spell Bonus per stack.  Spell Bonus is derived from the hunter's RAP which appears to be correct in the tooltip.  

**Current behaviour**: Scorpid Poison is currently doing 12 damage per tick, for a total of 60 damage, regardless of what gear I put on or take off.

Scorpid Poison does a base 55 damage over 10 seconds at max rank.  My pet currently has 219 Spell Bonus, Scorpid Poison should be doing 93.8 extra damage per stack over it's duration for a total of 148.86.

https://www.engadget.com/2007/08/08/bigredkitty-the-whole-scorpid-thing/
https://puu.sh/CT6ia/32514f1603.png

**Comment by The14me** [comment]
Rev.3478 still an issue.

**Comment by tsu-1** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/5398#issue-421843444

**Comment by Godmatik** [comment]
Scaling was fixed last year - closing
