### ISSUE TITLE
[Spell][Druid] Abolish Poison

### ISSUE THREAD

**Issue by jauho-1** [Atlantiss/NetherwingBugtracker#5281]
**Description**: Abolish Poison is not removing poisons after initial cast, despite reports of it being fixed 19 days ago.

**Current behaviour**: Abolish Poison removes 1 poison on initial cast, no poisons removed during ticking Abolish Poison buff.

**Expected behaviour**: Abolish Poison buff should attempt to remove 1 poison every 2 seconds.

**Comment by Godmatik** [comment]
Same is true for Abolish Disease

**Comment by bekonja** [comment]
Just tested on BG vs rogue. During 1 minute of uptime abolish cleansed 0 poisons, only initial aplication works.

**Comment by gabbat** [comment]
> Same is true for Abolish Disease

up until two days ago I am certain that abolish disease was working correctly in cenarion HC's, I run those every day and it always has worked. I did not check since

**Comment by Johnkeyz** [comment]
Just tested this while doing testing on Shiv, it still does not remove poisons (i had 0 in vile poisons at the time)

**Comment by Wolffenstein** [comment]
It worked but didnt display proper info. Fixed in rev 2882.

**Comment by Realnairoby** [comment]
https://vimeo.com/328854619

Thats not working for me. Could you please recheck it? Its completly broken. @Wolffenstein

**Comment by Realnairoby** [comment]
Please fuck druids in arena more without noticing for over a decade. How can it be possible that a simple bug isnt fixed since beta nor since release?

**Comment by Redpandaw** [comment]
could you fix it pls? this is game changing bug

**Comment by Wolffenstein** [comment]
Fixed in rev 2948.
