### ISSUE TITLE
[QUESTS] "A Little Help From My Friends" and "Tooga's Quest" (and probably other escort quests)

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#5356]
**Description**: 
The escort mobs that follow you for "A Little Help From My Friends" and "Tooga's Quest" match your speed regardless of how fast you are going. They should not be able to move that fast. I imagine this may affect other quests as well.

**Current behaviour**:
Mobs that follow you match your movement speed, meaning if you are mounted, they will keep up regardless of how fast you are moving.

**Expected behaviour**: 
Escort mobs should follow you but have a capped movement speed. Wowhead comments indicate around 110% of normal move speed

**Server Revision**: 
2879

**Comment by Evolvee** [comment]
@Wolffenstein core support needed -- currently it uses the follow generator

**Comment by Wolffenstein** [comment]
Fixed in rev 3368.

**Comment by Godmatik** [comment]
@Wolffenstein Still broken, just did Tooga quest, he matches my mounted speed while following me.

**Comment by Godmatik** [comment]
Rev 4022
Still an issue
