### ISSUE TITLE
[Raid][Karazhan] Kara Side B can be entered without clearing side A

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#5737]
**Current behaviour**:
Right now you can enter kara from side B, without clearing required bosses from side A. Moroes and Opera event.

**Expected behaviour**: 
You shouldn't be able to enter Kara B, without clearing main bosses (Moroes, Opera event)
![Screenshot_2](https://user-images.githubusercontent.com/43505196/57587354-fc508d80-7503-11e9-9c34-7a4e3895d6d9.png)

**Server Revision**: 
2950

**Comment by Wolffenstein** [comment]
Fixed in rev 2975.

**Comment by Firroth** [comment]
@Wolffenstein 
Problem is still there, entered Kara B without clearing A, today.

Rev 2984.
