### ISSUE TITLE
[Dungeon][NPC] Shadow Labs - Grandmaster Vorpil Adds/Teleport

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#6547]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**:

When he teleported us the animation played on our characters, but we did not actually get moved.

**Expected behaviour**: 

Should not add any mobs and teleport the players onto the platform properly.

Maybe related to https://github.com/Atlantiss/NetherwingBugtracker/issues/5886 

**Server Revision**: 3236

**Comment by Tereneckla** [comment]
Teleported me each time, but the two mobs sometimes do get added after the teleport.

**Comment by Drayo** [comment]
His yell seems to add mobs around him, like the questionable one Ambassador Hellmaw uses.

In my last test he added the group from the room before and the patrolling Fel Overseer. 

- His yell should not add any mobs, it is pure RP for his Summoning of Void walkers after all.

**Comment by Wolffenstein** [comment]
Fixed in rev 3396.

**Comment by Drayo** [comment]
Him adding his own room is correct and works. 

But he also adds some mobs from the connecting room before, these do not add when I tested it on retail. 

NW: https://youtu.be/0Jq19ImchP0
Retail: https://youtu.be/TFnI4X6Ee_w

Aside from the Fel Guard they can be skipped with a Priests "Mind Soothe", which is kind of a reward for smart play. But generally just like it was with Hellmaw, nobody would really associate these mobs with Vorpil. 
That makes it seem bugged rather than an attention to detail. I also can't find any info about these adding on Wowhead etc., but that's not a surprise because players back then did not skip much.

**Comment by Drayo** [comment]
- The issue with him adding mobs from the room before his own is still present.

- He also does not teleport players again. It seems like he teleports melee ranged players just fine, but ranged do not get moved.

https://www.youtube.com/watch?v=ZJy2oQ2a38g

**Comment by Wolffenstein** [comment]
Fixed in rev 3511.
