### ISSUE TITLE
TODO:  end of quest "11516"

### ISSUE THREAD

**Issue by Evolvee** [Atlantiss/NetherwingBugtracker#6646]
need to add proper fire gameobjects

wtb sniffs of the quest

**Comment by Evolvee** [comment]
@Wolffenstein 😢 https://youtu.be/khWyssRJy9w?t=228

**Comment by Godmatik** [comment]
Fire visuals for end of quest matches what i see in classic, perhaps was fixed at some point.

Closing.

**Comment by Evolvee** [comment]
Its not fixed, I just added a custom fire thats nowhere near how it should behave.
