### ISSUE TITLE
Gurubashi arena chest bug

### ISSUE THREAD

**Issue by llam0015** [Atlantiss/NetherwingBugtracker#6898]
Basically, the chest doesnt give the arena master trinket, i have the quest arena master, to collect 12 trinketts, but doesnt give any, just the 1st time, i picked like 7 times the chest in the correct hours of the chest appears, and never except the first time give it to me the arena master trinket, and according to this should give the arena master trinket every time i assume.

It gives to me silver coins and an object, but not the trinket.

**Comment by Evolvee** [comment]
@Wolffenstein probably a core issue since the item starts a quest so its being treated like already rewarded, therefore doesnt drop... i cant hackfix this

**Comment by llam0015** [comment]
just one more question: i know that is a bug and u do your best always, but its possible to take it back the trinkets? if you can track how many times i opened the chest? ty in advance, no matter if answer is positive or not, i just want to know XD

**Comment by Evolvee** [comment]
dont think so

**Comment by llam0015** [comment]
any news on the issue?

**Comment by llam0015** [comment]
as i been spoken with other players, it seems that players that doesnt speak at all with the guy at the arena, and didnt take any mission there, they can pick the trinket, but if u spoke with him and take the mission, u are not able to take any trinket, i even try to abandon the quest, but doesnt work at all

**Comment by Evolvee** [comment]
thats what i said above...

**Comment by Wolffenstein** [comment]
Fixed in rev 3341.

**Comment by llam0015** [comment]
is not fixed, i have the quest again, i picked the chest, it gives to me the things inside, but not the arena master

**Comment by Tereneckla** [comment]
Type .server info
We still are in revision 3338
