### ISSUE TITLE
[core][arena] After leaving the arena, all debuffs are still active (dots can kill you right after you end up out of arena)

### ISSUE THREAD

**Issue by Evolvee** [Atlantiss/NetherwingBugtracker#6916]

**Comment by Tereneckla** [comment]
Never taken damage from dots after arena before.
Debuff shows but no damage taken.

**Comment by Evolvee** [comment]
i saw someone die

**Comment by veekk** [comment]
even debuffs must be removed, even if they're deals 0 damage, Coex or hamstring pretty annoying :D

**Comment by Wolffenstein** [comment]
Fixed in rev 3368.

**Comment by raethkcj** [comment]
Not fixed, just had a full duration Frost Nova after leaving a battleground.

![image](https://user-images.githubusercontent.com/7716908/85456830-fdf0df80-b564-11ea-94fb-d61ba6d8a392.png)

**Comment by raethkcj** [comment]
Still broken on Karazhan

![image](https://user-images.githubusercontent.com/7716908/91645293-8f6b4a80-ea09-11ea-81bb-84bc0a2b9256.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 3520.
