### ISSUE TITLE
[Item] Libram of the Lightbringer

### ISSUE THREAD

**Issue by Cryingnugget** [Atlantiss/NetherwingBugtracker#7137]
Libram of the Lightbringer (28296) not working (PTR Testing)

Holy Light Calc-ish
(coeff *BH+min;maxHealvalue+Libram *coeff)*healincrease effects
so for HolyLight11:

1) without Libram
	((0,714 *1276)+(2196;2446))*1,12  = 3480 - 3760

2) with Libram
         ((0,714 *1276)+(2196;2446)+(87 *0,714))*1,12 = 3549 - 3829

While having the Libram equipped i never got any heal above the maxValue of 1) (3760), but a lot of casts below the minValue of 2) (3549), which should not be possible if the Libram was working.
DrDamage is backing up my mathz apart from some minor rounding errors 

Same issue for Totem of Spontaneous Regrowth (27544)
Blessed Book of Nagrand (25644) seems to work fine

only tested these 3 and only on ptr, no idea if it works on liverealm :^))
*IF* theres a source needed i found this one in the feenix bugtracker from 2012, they also mention some other items that might bug here aswell
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/1049

**Comment by Tereneckla** [comment]
Should increase the bonus healing used for the calculation of Holy Light healing by 87

**Comment by Wolffenstein** [comment]
Fixed in rev 3471.

**Comment by Cryingnugget** [comment]
Libram still not working
but now Holy Light downranks (rank 10 to rank 1) heal less than they should by default 
probably wrong coeffs?
