### ISSUE TITLE
[Spell] Wind Shock - removed on meele hit.

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#75]
[NPC] Bristlelimb Windcaller https://www.wowhead.com/npc=17184/bristlelimb-windcaller
[Spell] Wind Shock https://www.wowhead.com/spell=31272/wind-shock

**Current behaviour**:
Spell from this mob seems to be working fine, except there is a single issue with it. 
When spell is casted on player it deals damage - works fine, lasts 10 seconds - works fine, the issue is with it randomly being "dispeled" from the player. I play as a warrior, and I didn't have anyone in group who could dispel me or was in range to do it. From what I saw when mob meele hits you it will randomly dispel it from you, it can occur on first hit or on 3rd etc. or not at all. So far I only had 1 try where it lasted entire duration =10 seconds, rest was removed from me when mob meele hitted me.
Tested it several times to be sure.

**Expected behaviour**: 
This spell shouldn't be removed/dispeled on being hit by the caster, or anyone else. Only possible method of removal should be dispel by another player (priest/paladin) or just wait entire duration.

**Server Revision**: 
2019

**Comment by Wolffenstein** [comment]
Fixed in rev 2022.

**Comment by Firroth** [comment]
Bug came back and is working like before - being removed on meele hit.
