### ISSUE TITLE
(Karazhan 2.x) Faerie Fire (Feral) overrides Moonkin upgraded Faerie Fire

### ISSUE THREAD

**Issue by MartinBrandstrup** [Atlantiss/NetherwingBugtracker#7502]
**Description**: 
As per the title; the Feral Druid's Faerie Fire overrides any other Faerie Fire on the target if used.
I have seen a few instances where it works as intended; it seems to be random, but it is not foolproof and thus creates potential issues - especially in 25man raids.

**Current behaviour**:
Sometimes when using Faerie Fire (Feral) on a target already affected by a talented (https://tbcdb.com/?spell=33602) Faerie Fire it will override.

**Expected behaviour**: 
Being unable to cast the spell with the proper error message "A more powerful version is already in effect" if I remember correctly... something along those lines.

**Server Revision**: 
TBC 2.x

**Comment by Wolffenstein** [comment]
Fixed in rev 3521.

**Comment by Godmatik** [comment]
Still not fixed after latest server update.

Faerie Fires from a feral druid are overwriting my Improved Faerie Fire
