### ISSUE TITLE
Gladiator's Gavel not 2.0 stats

### ISSUE THREAD

**Issue by Fierywind** [Atlantiss/NetherwingBugtracker#7532]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: the Gladiator's Gavel does not have 2.0 adjusted itemization

**Current behaviour**: I am unable to take screenshots of the client, but it has 28 stamina, 18 intellect, 18 resil, and 199 spellpower

**Expected behaviour**: It share the adjusted stats of other weapons such as Gladiator's Spellblade at 24 stam, 16 int, 16 resil, and 187 spellpower.

**Server Revision**: 3528

**Comment by Wolffenstein** [comment]
Source?

**Comment by Wolffenstein** [comment]
It's not in the game though?

**Comment by Tereneckla** [comment]
It is and all the caster weapons have post 2.1 values.

**Comment by Tereneckla** [comment]
It is and shouldn't be

**Comment by Wolffenstein** [comment]
Fixed in rev 3529.

**Comment by raethkcj** [comment]
It's still in game and tooltip still shows 199 damage after freshly cleared cache. Rev 3534
