### ISSUE TITLE
[Hunter] Hunter shots are still consuming GCD, but not the shot.

### ISSUE THREAD

**Issue by gunzbngbng** [Atlantiss/NetherwingBugtracker#7643]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Often, if you attempt to fire a shot while your autoshot is paused, you will incur a GCD and the shot will not fire.  It is largely affecting PvP and Arena, as autoshot is commonly on pause while positioning and kiting.  It seems to sometimes cause a "target not facing right way" error.  It was previously in this bug report that was marked as closed.  https://github.com/Atlantiss/NetherwingBugtracker/issues/7563

**Current behaviour**:  It seems that autoshot being paused or in windup is preventing other shots and incurring a GCD.  This also sometimes happens at the end of aimed shot, the autoshot queue seems to often incur a GCD after firing a 3s cast aimed shot.

**Expected behaviour**: While autoshot is paused or in windup, shots should fire when the button is pressed.  Also, if you cast an instant spell, like arcane shot, arcane shot should instantly fire and autoshot should continue to fire at it's normal interval.  Arcane shot should not delay autoshot and autoshot should not delay arcane shot, as it currently appears to.

**Server Revision**: 3186

**Comment by Wolffenstein** [comment]
Hopefully fixed in rev 3543 (i can't reproduce it).

**Comment by gunzbngbng** [comment]
@Wolffenstein It is NOT fixed.

https://clips.twitch.tv/LightAggressiveClintmullinsPanicBasket
