### ISSUE TITLE
All NPCs - "Fleeing" will take priority over all other actions, including spell casts

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8046]
**Currently:**
Mobs that are set to flee at a certain percentage of health, many humanoids in particular, will do so and interrupt their own casts or other abilities if need be. 
For example humanoids that heal (like Galak Windchaser https://www.wowhead.com/wotlk/npc=4096/galak-windchaser) will often channel a heal when they are low health as part of their script, but if you bring them to an even lower health threshold to where they flee, they will interrupt their own cast and run away.

**How it should work:**
Mobs should complete their casts before doing the flee script, consistent with classic behavior

**Comment by Wolffenstein** [comment]
Fixed in rev 3690.

**Comment by Godmatik** [comment]
@Wolffenstein Partially fixed, the mob will initiate their flee script after the heal finishes, if a heal brings them above the flee threshold they shouldn't try and flee still.
