### ISSUE TITLE
[AURA] Arcane Intellect stacking

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8163]
**Description**: 
Arcane Intellect and Arcane Brilliance are currently stacking

**Current behaviour**:
Cast Arcane Brilliance (group buff), then Arcane intellect - notice you have both buffs active. Both are providing +intellect

**Expected behaviour**: 
Can't have both up at the same time.
This may also be impacting other buffs although I am not certain.

**Server Revision**: 
3702

**Comment by duzyizly** [comment]
![image](https://user-images.githubusercontent.com/43931626/223371297-a3e2d5b3-460a-47ef-9a54-f3a8a36193de.png)
Same with Gift/mark fo the wild. Sounds like global.

**Comment by duzyizly** [comment]
![image](https://user-images.githubusercontent.com/43931626/223373028-ea5b1b51-1df5-4ac5-90f2-d6bb5dbed142.png)
Fortitude stacks, spirit buff does not.

**Comment by Wolffenstein** [comment]
Should be fixed

**Comment by duzyizly** [comment]
Mage and priest buffs get fixed.
Druid still broken.
@Wolffenstein 

![image](https://user-images.githubusercontent.com/43931626/223564970-94b3e23c-38ad-420c-8888-3eaf29d07c43.png)

**Comment by Wolffenstein** [comment]
Fixed
