### ISSUE TITLE
Silithus: The Four Dukes - major quest chain will not start/work

### ISSUE THREAD

**Issue by twatllama** [Atlantiss/NetherwingBugtracker#8385]
(https://www.wowhead.com/classic/quest=8538/the-four-dukes)

**Description**: 
This is a critical quest chain to attain a strong farming ring (for Paladins) called Wrath of Cenarius. As it currently exists, this ring is unattainable as it requires you to have quest reward marks (one in particular called Mark of Cenarius) which is unattainable from this associated quest not functioning.

**Current behaviour**:
Dukes are not spawnable, nor is the quest itself able to be picked up as the [Tactical Task Briefing V] will not provide the quest. The spawning issue is a separate one involving the 3 Twilight clothing pieces which do not make the stones to summon these dukes spawn, be interactable, nor work.

**Expected behaviour**:
As you hand in various other Tactical Task Briefing quests, they provide an item which has a chance of spawning the [Tactical Task Briefing V], right clicking this item will start the quest "The Four Dukes".

**Server Revision**: 
2.4.3

**Comment by twatllama** [comment]
The following parts of the chain also do not start any quest when right clicked, and thus are also limited the way marks can be attained in game:
Logistics Task Briefing V
Logistics Task Briefing VI
Logistics Task Briefing X
Tactical Task Briefing VII
Tactical Task Briefing VIII
Tactical Task Briefing X

I have not attained every task briefing (as they are chains from these chains which are not working), but I know that the above do not open/provide a quest. There is no error code generated.

On a positive note, all the Combat Task Briefings work, provide a quest and are completable as I have done all 12 of them.

**Comment by ashido96** [comment]
Confirmed that these quest giving items do nothing when right clicked.

**Comment by Wolffenstein** [comment]
Fixed in rev 3831.

**Comment by StaticHispanic** [comment]
Some Logistics tasks still dont work. 
Also @twatllama , were you able to get the ring after it was fixed? The Champion's Battlegear doesnt show up for a bunch of us.
