### ISSUE TITLE
Bugged Quest: Dead Man's Plea / Stratholme 

### ISSUE THREAD

**Issue by romkaromi** [Atlantiss/NetherwingBugtracker#8504]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Stratholme] Dead Man's Plea)
[//]: # ([NPC] Ysida Harmon)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

Quest: Dead Man's Plea / Stratholme

NPC: Ysida Harmon

**Current behaviour**:

I have finished the quest "Dead Man's Plea" (45min Baron Run) twice, but i can't turn in the quest at Ysida Harmon. She is not coming out of cage to turn in the quest.

**Expected behaviour**: 

The NPC is supposed to walk out of the cage with yellow questionmark, so that one can turn in the quest. But she remains in the cage, eventhough the quest is marked as 'complete' in questlog. Tried to do the quest twice now, same issue.

**Server Revision**: 

3811

**Comment by Wolffenstein** [comment]
Did the cage open at least?

**Comment by Wolffenstein** [comment]
Fixed in rev 3815.

**Comment by romkaromi** [comment]
update: just completed the 45 min baron run and its still the same issue :(
