### ISSUE TITLE
[Pet] - No error message when feeding pet food that is too high for its level

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8541]
**Current behaviour**:
If you feed a pet some food that is too high for its level, there is no error message.

This causes confusion sometimes with low level new hunters because they feed the wrong food and think it's working fine until their pet runs away (I see some questions on discord occasionally on it)

**Expected behaviour**: 
Should be an error message
"This food is too high level for your pet"

https://github.com/Atlantiss/NetherwingBugtracker/issues/1917

**Comment by Wolffenstein** [comment]
Fixed in rev 3830.

**Comment by Godmatik** [comment]
Rev 4014 - not fully fixed.
The food is not consumed - however there needs to be an error message shown.

**Comment by Godmatik** [comment]
Fixed
