### ISSUE TITLE
[NPC] Dungeon mobs are dropping incorrect gold amounts

### ISSUE THREAD

**Issue by MecAtlantiss** [Atlantiss/NetherwingBugtracker#8556]
**Description**: Undead mobs in Stratholme are dropping anywhere from 1s40c to 8s, when they should be dropping 9s to 1g. You've recently stealth nerfed grey drops from Stratholme, which has caused Stratholme to be far lower gold per hour than would be blizzlike, because gold drops are bugged. The advantageously bugged grey/green drops were offsetting the disadvantageously bugged gold drops, but now the gold per hour is incorrectly too low. I'm guessing this bug affects more than just Stratholme, but haven't tested to confirm.

**Current behaviour**: This is loot in a 2 man party in Stratholme currently, so the current drop amount double what's shown here:
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/16357005/c0208f2f-06f6-4b32-917a-e51705477f85)

**Expected behaviour**: Undead mobs in Stratholme should be dropping around 9s to 1g, as seen in this tbcc video: https://www.youtube.com/watch?v=khpkx8PpkJQ&t=135s

**Server Revision**: 3827

**Comment by Wolffenstein** [comment]
Fixed in rev 3833.

**Comment by MecAtlantiss** [comment]
Not fixed on 3836.
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/16357005/6b8af66c-aa69-4342-9f3e-8638c5e80833)
