### ISSUE TITLE
Rogue class trinket internal CD

### ISSUE THREAD

**Issue by Jedliad2** [Atlantiss/NetherwingBugtracker#8601]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The rogue trinket Warp-Spring Coil has longer internal cooldown than intended
**Current behaviour**:
The trinket seems to have internal cooldown of 45sec when tested (Easy too test on spamming sap on a mob as trinket has 25% proc on abilities)
**Expected behaviour**: 
The Trinket should have 30 sec internal cooldown 
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3848.

**Comment by Jedliad2** [comment]
It is not fixed. I just tested it internal cd is still not 30 sec but 45. trinket uptime should be 50% at the best case now it is 33%.

**Comment by Jedliad2** [comment]
in case im adding the logs of rogue from classic. It is visible that window between procs is about 15 sec (Arcane brilliance looking buff)

https://classic.warcraftlogs.com/reports/7RhqtzPXZ49dNbVg#fight=40&type=auras&source=18&view=timeline

**Comment by Godmatik** [comment]
You need to wait until the server restarts with the newest update
