### ISSUE TITLE
Bhag'thera, 728, Stranglethorn Vale

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#861]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
the monster seems to be spawning at different locations, where it shouldnt be spawning at all (even with the different spawpoints). It might be a conflict with dynamic respawn, where it was added to normal mobs' spawnpoint.
**Current behaviour**:
bhag'thera is not spawning correctly, at a timer or fixed place/places
**Expected behaviour**: 
Should have a unique spawntimer, not shared with other mobs.
**Server Revision**:

**Comment by The14me** [comment]
Confirm,maybe some issue with shared spawn.

**Comment by aresbrutus** [comment]
She spawns and roams around the same areas like on retail: https://i.imgur.com/04KJUG3.jpg

And she also spawned in one of the other points when I killed her, so working for me. Please retest and reply here again if the issue is present.

**Comment by aresbrutus** [comment]
Seems the issue was due to some leftover stock respawn system. This will be corrected in one of the next updates.

**Comment by aplouding** [comment]
Bump. This needs to be fixed. Still not spawning correctly. Waited 2+ hours for her to spawn.

**Comment by aplouding** [comment]
update: she was found at Zul'Gurub, way off her track
