### ISSUE TITLE
[NPC] Skywing

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8873]
**Current behaviour**:
When doing the quest Skywing - the bird NPC gets stuck during the escort at these coords, and the quest can not be completed:

![skywing](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/a8ad009b-b382-4809-ab78-775dbbff79e4)

Rev 3956

**Comment by Godmatik** [comment]
Rev 4016 - still an issue

**Comment by Godmatik** [comment]
Possibly resolved with movement rework, am no longer able to reproduce

**Comment by Godmatik** [comment]
It's back

**Comment by Dailybg** [comment]
https://cdn.discordapp.com/attachments/1063133089657798730/1347846973054783509/image.png?ex=67cdf890&is=67cca710&hm=2aaa98fdedadb18e27cecfbb1d3816edecac31fe4fef00f7db39638c83ace4af&

Still an issue, Skywing bugged after fighting a mob, right after saying he's ready to enter the tree stairs. The reason there are two bodies nearby is because I waited for respawn if it helps, but it didn't.

**Comment by Godmatik** [comment]
Fixed in movement branch update, being applied tomorrow morning
