### ISSUE TITLE
[Spell][Warrior] Sweeping Strikes has a ridiculous range for hitting a target

### ISSUE THREAD

**Issue by f0xlife** [Atlantiss/NetherwingBugtracker#9272]
# Abstraction
I was testing on the modern client, version 2.5.2.

The tooltip of the Sweeping Strikes ability says:
> Your next 10 melee attacks strike an additional nearby opponent.

![Image](https://github.com/user-attachments/assets/2fe38476-9f27-43c8-9d13-ddcd56e7bb09)
So my question is: why is it able to hit the far target if the player stands closer to the group of targets?

# Result
When I hit the nearest Test Dummy in the middle of the five with auto attacks, I can also hit the far-right Test Dummy if you look at the picture below.
![Image](https://github.com/user-attachments/assets/aab860f6-3c51-4b18-b49f-7245dd956d60)

I step back a bit. This is the maximum distance at which I can reach the Test Dummy on the right.
![Image](https://github.com/user-attachments/assets/a551a267-4b3a-4677-8e91-641d16e2e828)

I step back more and now it never happens. It looks like this is caused by the range of the hitbox. 
![Image](https://github.com/user-attachments/assets/1e2b96b7-1a62-4ec5-8867-3541864755df)

# Conclusion
I have no idea if this is the correct behavior for the ability, but to me, it looks buggy

**Comment by Godmatik** [comment]
Probably a side-effect of this fix:

https://github.com/Atlantiss/NetherwingBugtracker/issues/9209

**Comment by Godmatik** [comment]
Fixed in rev 4026

**Comment by f0xlife** [comment]
@Godmatik It is still happens on 4026
![Image](https://github.com/user-attachments/assets/3090c812-5a84-4eee-be69-c8516acdedb5)

**Comment by Wolffenstein** [comment]
Fixed in rev 4029.
