### ISSUE TITLE
[Spell][Paladin] Seal of Righteousness static coefficient

### ISSUE THREAD

**Issue by Silbotronic** [Atlantiss/NetherwingBugtracker#9415]
How it works currently: Seal of Righteousness scales with 10% of your spell damage regardless of weapon speed or whether you're using a 1-hander or 2-hander. For example, with 54 spell damage i get exactly 5 more seal damage than the tooltip, Judgement of the Crusader only adds 12 damage (129 increased holy damage taken) etc.

How it should work: Seal of Righteousness scales with 9.2% * weapon speed if you're wielding a 1-hander and 10.8% * weapon speed if you're wielding a 2-hander. 

This issue was fixed in the previous tbc server so it's odd that it has cropped up again.

Server revision: 4036

https://www.wowhead.com/tbc/spell=27155/seal-of-righteousness
https://wowwiki-archive.fandom.com/wiki/Spell_power_coefficient?oldid=1549180#Paladin_coefficients

**Comment by Wolffenstein** [comment]
Fixed in rev 4038.

**Comment by Silbotronic** [comment]
> Fixed in rev 4038.

SoR still doesn't scale with weapon speed, only the SotC judgement part was fixed, at least on my end.

**Comment by Wolffenstein** [comment]
Fixed in rev 4039.
