### ISSUE TITLE
Double thrown attack

### ISSUE THREAD

**Issue by Sbdasukas** [Atlantiss/NetherwingBugtracker#9565]
If you spam thrown weapon attack, it goes out in multiples of 2. Both attacks do regular damage. Reprodicible with perceived certainty. Done using Gladiator's War Edge.

2.4 client.

https://imgur.com/a/ZtNssSH

**Comment by Sbdasukas** [comment]
Combat log can be seen better here:

https://imgur.com/a/CpQhtiX

the animation also doubles, two animations in quick succession

**Comment by Wolffenstein** [comment]
Fixed in rev 4047.

**Comment by f0xlife** [comment]
Still an issue rev. 4051

![Image](https://github.com/user-attachments/assets/adfc076e-5089-4b1e-b6cd-b2ede03b629a)

https://github.com/user-attachments/assets/5f34c542-4835-41c0-a984-5cdaf5f28e74
